### ISSUE TITLE
LiveWS要小心Error的问题

### ISSUE THREAD

**Issue by simon300000** [dd-center/SuperSpider#7]
https://github.com/dd-center/SuperSpider/blob/b7ad1dff52eed736014aca490efa41533d8e460e/packages/superspider-predb/modules/rdb.js#L33

可能会把整个程序炸掉，需要用`ws.on('error'`抓住
以及可以直接用`ws.on(data.cmd`来监听特定cmd

**Comment by ilharp** [comment]
所有package在index一开始就已经捕捉了unexpectedexception。
尽管如此捕捉ws的error也是必要的。之后我有时间的话会进行修改。

**Comment by simon300000** [comment]
升级到2.0.0后应该不需要担心吧
