### ISSUE TITLE
这可是连接了不少ws

### ISSUE THREAD

**Issue by simon300000** [dd-center/SuperSpider#8]
https://github.com/dd-center/SuperSpider/blob/b7ad1dff52eed736014aca490efa41533d8e460e/packages/superspider-mdb/utils/rws.js#L2
https://github.com/dd-center/SuperSpider/blob/b7ad1dff52eed736014aca490efa41533d8e460e/packages/superspider-db/utils/rws.js#L2
https://github.com/dd-center/SuperSpider/blob/b7ad1dff52eed736014aca490efa41533d8e460e/packages/superspider-predb/utils/rws.js#L2

我不知道哪些文件是在用的，但是稍微估计一下这时上千个连接了，每个relay都是几百个连接呀

**Comment by ilharp** [comment]
是的，这确实是一个严重的问题。之后我有时间的话会进行修改。

**Comment by ilharp** [comment]
d3ca55ae208a828880d9f476c3ea769e6777bf56
中已经修复了这个问题。
同时db模块已经弃用了。
