### ISSUE TITLE
我有些疑惑，你把rws干的又干了一遍

### ISSUE THREAD

**Issue by simon300000** [dd-center/SuperSpider#9]
https://github.com/dd-center/SuperSpider/blob/b7ad1dff52eed736014aca490efa41533d8e460e/packages/superspider-predb/modules/rdb.js#L33
这又开了LiveWS吗？relay可能已经开了一样的LiveWS呀

**Comment by ilharp** [comment]
是的，这确实是一个严重的问题。之后我有时间的话会进行修改。

**Comment by ilharp** [comment]
d3ca55ae208a828880d9f476c3ea769e6777bf56
中已经修复了这个问题。
